version: '3.8'

services:
  nodejs_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - mongodb 

  mongodb:
    image: mongo:4
    env_file: .env
    expose:
      - "27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
